

# .travis.yml using container-based infrastructure
# travis configuration file courtesy of Jan Tilly:
# https://github.com/jtilly/R-travis-container-example

## Trying 2016 update from RStudio: <https://blog.rstudio.com/2016/03/09/r-on-travis-ci/>

language: r
sudo: false
cache: packages

# install the package and dependencies:
# - create directory for R libraries (if not already exists)
# - create .Renviron with location of R libraries
# - define R repository in .Rprofile
# - add .travis.yml to .Rbuildignore
# - install devtools if not already installed
# - install covr if not already installed
# - update all installed packages

r_packages:
  - lintr

# install:
#  - mkdir -p ~/Rlib
#  - echo 'R_LIBS=~/Rlib' > .Renviron
#  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
#  - echo '.travis.yml' > .Rbuildignore
#  - Rscript -e 'if(!"devtools" %in% rownames(installed.packages())) { install.packages("devtools", dependencies = TRUE) }'
#  - Rscript -e 'if(!"covr" %in% rownames(installed.packages())) { install.packages("covr", dependencies = TRUE) }'
#  - Rscript -e 'if(!"lintr" %in% rownames(installed.packages())) { install.packages("lintr", dependencies = TRUE) }'
#  - Rscript -e 'update.packages(ask = FALSE)'


# Lint
script:
  - ./travis-linter.sh
